name: Remote SSH Command and CI Workflow

on:
    push:
        branches:
            - main # или ваша основная ветка
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Executing remote SSH commands using password
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: whoami

            - name: Deploy to server using SSH with password
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd /home/ubuntu/weekly-streaming &&
                      git checkout dev &&           # Переключиться на ветку dev
                      git pull &&                   # Забрать последние изменения
                      cd .. &&                      # Вернуться на уровень выше
                      docker-compose down &&        # Остановить текущие контейнеры
                      docker-compose build &&       # Пересобрать контейнеры
                      docker-compose up -d         # Запустить контейнеры в фоновом режиме
