name: CI Workflow

on:
    push:
        branches:
            - main # или ваша основная ветка
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Шаг 1: Проверка кода из репозитория
            - name: Checkout code
              uses: actions/checkout@v2

            # Шаг 5: (Опционально) Деплой на сервер
            # Это пример для деплоя на сервер через SSH
            # Необходимо добавить секреты SSH ключа в Settings > Secrets
            - name: Deploy to server
              if: github.ref == 'refs/heads/main' # Только при пуше в main ветку
              run: |
                  ssh -i ${{ secrets.SSH_PRIVATE_KEY }} robot@92.112.180.234"
                    cd /home/ubuntu/weekly-streaming && 
                    git checkout dev &&       # Переключаемся на ветку dev
                    git pull &&               # Получаем последние изменения
                    cd .. &&                  # Выходим на уровень выше
                    docker-compose down &&    # Останавливаем текущие контейнеры
                    docker-compose build &&   # Пересобираем контейнеры
                    docker-compose up -d"     # Запускаем контейнеры в фоновом режиме
