name: CI Workflow

on:
    push:
        branches:
            - main # or your main branch
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to server
              if: github.ref == 'refs/heads/main' # Only on push to main branch
              uses: webfactory/ssh-deploy-action@v0.5.1
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: 22
                  script: |
                      cd /home/ubuntu/weekly-streaming && 
                      git checkout dev &&           # Switch to dev branch
                      git pull &&                   # Pull the latest changes
                      cd .. &&                      # Go up one directory
                      docker-compose down &&        # Stop current containers
                      docker-compose build &&       # Rebuild containers
                      docker-compose up -d         # Start containers in detached mode
